### ISSUE TITLE
vimcat can't open any file

### ISSUE THREAD

**Issue by peterwu** [Smattr/vimcat#30]
I've tried various file types, such as .c, .cpp, .py, .txt, .rst, Makefile, etc. None worked. The error message is:

> failed: Operation not supported

Is vimcat in a usable condition at this point?

**Comment by Smattr** [comment]
Thanks for trying out Vimcat! I think you have the distinguished honour of being the first not-me bug reporter :)

I built Vimcat primarily to support something else I'm working on, https://github.com/Smattr/clink. But it's intended to work on any type of file. I wasn't aware of any outstanding bugs until this issue.

Can I know a bit more about your environment? What operating system, terminal emulator, and Vim version are you using?

You can also try the `--debug` flag. If you're knowledgeable about ANSI terminal codes, this gives you a way to observe what Vimcat is seeing Vim do.

**Comment by peterwu** [comment]
Hi! :-)

I'm running kitty v0.25.2 on Fedora Linux 36. Vim is v9.0.049. 

Here is what I did on my side:
- Downloaded vimcat-2022.06.23.tar.gz
- cmake -B build -S .
- cmake --build build
- go to the build/vimcat dir
- ./vimcat manpage.c
- error!

Here is what --debug reports:
```
 ./vimcat --debug manpage.c
[VIMCAT] libvimcat/src/read.c:311: manpage.c has 244 rows and 73 columns
[VIMCAT] libvimcat/src/read.c:325: clamping terminal columns from 73 to 80
[VIMCAT] libvimcat/src/read.c:240: running Vim with '+set lines=245', '+set columns=80' on manpage.c
[VIMCAT] libvimcat/src/read.c:270: vim is PID 374263
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?1000h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?1049h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[>4;2m
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?1h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?2004h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?1004h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[1;24r
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?12h
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[?12l
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[22;2t
[VIMCAT] libvimcat/src/term.c:540: ignoring private sequence <esc>[22;1t
[VIMCAT] libvimcat/src/term.c:610: processing <esc>[27m
[VIMCAT] libvimcat/src/term.c:610: processing <esc>[23m
[VIMCAT] libvimcat/src/term.c:610: processing <esc>[29m
[VIMCAT] libvimcat/src/term.c:610: processing <esc>[m
[VIMCAT] libvimcat/src/term.c:610: processing <esc>[38;2;0;0;0m
[VIMCAT] libvimcat/src/term.c:521: unsupported SGR attribute <esc>[38m
[VIMCAT] libvimcat/src/read.c:383: waiting for Vim to exit...
failed: Operation not supported 
```

**Comment by Smattr** [comment]
Ah yes, I can see what's going on here. Thanks!

The issue is that Vim is using 24-bit bit colour, while Vimcat's internal virtual terminal emulator only supports 2-bit, 8-colour, 16-colour, and 8-bit colour. When moving up from 16-colour to support 8-bit colour I couldn't get Vim to produce 24-bit colour sequences, and I realized my terminal did not support 24-bit colour. I surveyed the terminals at the time and concluded very few did, with Kitty being one of the exceptions. I guess I mistakenly assumed no one would ever try Vimcat on a 24-bit colour terminal!

Implementing it shouldn't be too hard, but might need a few days. I think I have a Fedora 36 machine lying around, so I can probably replicate your environment too. Stay tuned...

**Comment by Smattr** [comment]
I replicated what I think is your exact environment, but surprisingly everything works. Clearly my Kitty is somehow not passing 24-bit colour support on to Vim, but I'm not sure how or why.

Meanwhile I wrote what I think are the required changes in https://github.com/Smattr/vimcat/pull/32. Instead of my trying to replicate your exact conditions, do you want to try the changes in that PR and see if they solve your problem?

**Comment by peterwu** [comment]
I tried the PR but the problem is still there. --debug seems to print out a lot more information this time but unfortunately, github doesn't allow me to post the entire log as its length exceeds the limit of 65536 characters.

**Comment by Smattr** [comment]
🤔  if the result is unchanged, it suggests to me [the code I wrote to detect `38;2;...`](https://github.com/Smattr/vimcat/pull/32/files#diff-6540e906d6d176ee4da195090951ccecf2938477ebc7fc0534375c70d510c96cR695-R716) is not matching correctly and execution is still falling through to the general `...m` logic that calls `process_m`.

I'll meddle with my Fedora+Kitty setup some more and see if I can get into 24-bit colour mode. In the meantime, please let me know if you have other ideas of what may be going on here.

**Comment by Smattr** [comment]
By the way, in your Vim what does `:set t_Co` say?

**Comment by peterwu** [comment]
> By the way, in your Vim what does `:set t_Co` say?

t_Co=256

**Comment by Smattr** [comment]
Hm well now the plot thickens. `t_Co=256` means 256-colour (i.e. 8-bit colour) mode. So Vim shouldn't even be emitting 24-bit colour sequences (I think). We also test all this in the test suite. Does `make check` run correctly for you? If it does or it doesn't, this doesn't conclusively prove anything, but it gives us another clue in this riddle.

**Comment by peterwu** [comment]
Where should I run `make check`? The cmake generated makefile doesn't have a `check` target.

**Comment by Smattr** [comment]
The CMake configuration has some logic where it disables `make check` if you don't have Python or if you don't have Pytest. Diagnostics for this could probably be improved. If you don't have Pytest and can't easily install it, I can keep plugging away on my side and see what I can learn.

**Comment by Smattr** [comment]
Aha I think I have (partially) cracked this. I couldn't get Vim to produce 24-bit colours because I was running without a ~/.vimrc. After putting `set termguicolors` in that I get 24-bit colours.

So one obstacle bypassed: I can repro your original issue. Except what's in the smattr/A7DE0E27-59E3-48F2-A6DC-596D27B7F063 branch currently solves it for me. There's clearly something more going on here.

Can I know more about what's in your ~/.vimrc? And/or can you try with a ~/.vimrc that contains only `set temguicolors` and report the results?

**Comment by peterwu** [comment]
My vimrc can be found at https://github.com/peterwu/dotfiles/blob/master/vim/vimrc. 

I'll give it a try with only `set termguicolors` and report back.

**Comment by peterwu** [comment]
I tested with only `set termguicolors` and your code worked! 

So it must be something else that prevents vimcat from working properly.

**Comment by Smattr** [comment]
Ah excellent! So it looks like the changes in that branch get us past the first problem.

The next thing I was going to try was bisecting your vimrc (removing and readding parts of it until I narrow down which line(s) are causing the issue), but I noticed you've got a lot of plugins and whatnot enabled that will be difficult for me to replicate. Any chance you could try this on your side?

My current guess is either one of the plugins of some folding. You can see how Vimcat puppets Vim [here](https://github.com/Smattr/vimcat/blob/c79b80dd5a79a95459322a2a208c43e84c14fb03/libvimcat/src/read.c#L207-L253) which might give you some ideas of the cause too.

**Comment by peterwu** [comment]
I further narrowed down the problem a little bit by disabling all the plugins that I have and removing all the plugin related configs in vimrc. So, I ended up having these in vimrc.

```
" defaults
source $VIMRUNTIME/defaults.vim

" options
set number relativenumber lazyredraw showmatch hidden hlsearch
set smartindent expandtab tabstop=8 shiftwidth=4 softtabstop=0
set smartcase ignorecase shortmess+=I title mouse=a laststatus=2
set noshowmode nolist listchars=trail:·,tab:»·
set cursorline termguicolors path+=**
set completeopt=menu,menuone,noinsert,noselect
set viewoptions=folds,cursor
set sessionoptions=folds
set viminfo+=n~/.vim/cache/viminfo

highlight CursorLine   cterm=NONE ctermbg=NONE ctermfg=NONE
highlight CursorLineNr cterm=NONE ctermbg=NONE ctermfg=NONE
```

Now, if I run your vimcat, the error shows up. Again, --debug reports a lot of information and the last few lines are:
```
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[?1000l
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[?2004l
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[>4;m
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[?2004h
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[>4;2m
[VIMCAT] libvimcat/src/term.c:599: ignoring private sequence <esc>[?1000h
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[38;2;165;42;42m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[38;2;46;139;87m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[38;2;46;139;87m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[38;2;255;0;255m
[VIMCAT] libvimcat/src/term.c:669: processing <esc>[m
[VIMCAT] libvimcat/src/term.c:930: unsupported escape sequence
[VIMCAT] libvimcat/src/read.c:373: `rc != 0` failed (current errno is 2)
[VIMCAT] libvimcat/src/read.c:383: waiting for Vim to exit...
failed: Operation not supported
```

**Comment by peterwu** [comment]
OK. I think I found the culprit:
```
set title
```
If this is turned on, then the error occurs.

**Comment by Smattr** [comment]
Yes!! I can repro this with `set title`! Vim seems to be sending an Operating System Command (OSC), `\033]...`. I don't know what it's trying to do but maybe query the foreground colour or the background colour. Annoyingly,  past me wrote this part of the code to simply debug print `unsupported escape sequence` without including the actual sequence it's choking on.

I'll investigate what's going on here and see if we can get both more informative debugging messages and a solution. I'll also merge the 24-bit colour support branch which seems to work. Thanks for tracking down the culprit in this whodunnit!

**Comment by peterwu** [comment]
My thought from another perspective: Since there are tons of options in vim, you may want to consider a set of options that vimcat supports as a whitelist. Under this assumption/baseline, it'll be a lot more manageable and predictable for the program to function as expected. 

In the case of `set title`, it doesn't make much sense for vimcat to support this vim feature. vimcat functions as an alternative to the standard cat command, which doesn't modify the title of a terminal emulator at all.  

Just my 2 cents.

**Comment by Smattr** [comment]
Yes, I thought a bit about this before. But one of the goals of Vimcat was to render exactly as Vim would, allowing anything and everything (e.g. dynamic Vimscript that introduces custom highlighting rules).

There's definitely a sort of "buyer beware" thing implicit here though, that users need to be aware it's literally running Vim under the hood and the outcomes may surprise them. I'll think about whether it should initially come configured in some "safe" mode or have a more obvious warning about what's happening.

**Comment by Smattr** [comment]
OK, do you want to try the latest in the `main` branch and let me know if it works?

**Comment by peterwu** [comment]
I just tried the latest and it worked like a charm!

**Comment by Smattr** [comment]
Great! Looks like 7cb994645581eac8346b135fc2614cc6a3f54221 fixed it.

Thanks again for helping debug this one, and let me know if you run into any more problems with Vimcat!
